// <auto-generated />
namespace E_CommerceWebSite.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class eCommerceConfigs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(eCommerceConfigs));
        
        string IMigrationMetadata.Id
        {
            get { return "201912291744377_eCommerceConfigs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
